#!/usr/bin/python3
import configparser
config = configparser.ConfigParser()
config['Switches'] = {}
switches = config['Switches']
switches['hostname1'] = 'Local_Switch'
switches['hostname2'] = 'IT_Network'
switches['hostname3'] = 'MGMT_Network'
switches['hostname4'] = 'ACCT_Network'
config['Switches:vars'] = {}
switchvars = config['Switches:vars']
switchvars['RAM'] = '512MB'
switchvars['vCPU'] = '1'
switchvars['QEMU'] = '/usr/bin/qemu-system-x86_64(v4.2.1)'
switchvars['boot'] = 'CD/DVD-ROM or HDD'
switchvars['onclose'] = 'Power off the VM'
switchvars['console'] = 'telnet'
switchvars['adapters'] = '13'
switchvars['type'] = 'realtek 8139 ethernet (rtl8139)'
switchvars['replicateQEMU'] = 'on'
switchvars['MAC1'] = '0c:1c:b2:85:00:00'
switchvars['MAC2'] = '0c:cc:78:5d:00:00'
switchvars['MAC3'] = '0c:40:34:07:00:00'
switchvars['MAC4'] = '0c:e0:f2:0b:00:00'
switchvars['MAC5'] = '0c:c0:5e:66:00:00'
config['TestBoxes'] = {}
boxes = config['TestBoxes']
boxes['box1'] = 'Test_Box_1'
boxes['box2'] = 'Test_Box_2'
config['WindowsDesktops'] = {}
windows = config['WindowsDesktops']
windows['host1'] = 'WindowsDesktop-1'
switchvars['host2'] = 'WindowsDesktop-2'
switchvars['host3'] = 'WindowsDesktop-3'
switchvars['host4'] = 'WindowsDesktop-4'
config['WindowsDesktops:vars'] = {}
windowsvars = config['WindowsDesktops:vars']
windowsvars['RAM'] = '4096MB'
windowsvars['vCPU'] = '2'
windowsvars['QEMU'] = '/bin/qemu-system-86_64(v4.2.1)'
windowsvars['boot'] = 'HDD'
windowsvars['onclose'] = 'Send the shutdown signal (ACPI)'
windowsvars['console'] = 'vnc'
windowsvars['adapters'] = '1'
windowsvars['type'] = 'Intel Gigabit Ethernet (e1000)'
windowsvars['replicateQEMU'] = 'on'
windowsvars['MAC1'] = '0c:4b:3c:0a:00:00'
windowsvars['MAC2'] = '0c:59:fd:86:00:00'
windowsvars['MAC3'] = '0c:e2:07:f3:00:00'
windowsvars['MAC4'] = '0c:46:74:35:00:00'
config['TestBoxes:vars'] = {}
boxesvars = config['TestBoxes:vars']
boxesvars['RAM'] = '4096MB'
boxesvars['vCPU'] = '2'
boxesvars['QEMU'] = '/bin/qemu-system-86_64(v4.2.1)'
boxesvars['boot'] = 'HDD'
boxesvars['onclose'] = 'Send the shutdown signal (ACPI)'
boxesvars['console'] = 'vnc'
boxesvars['adapters'] = '1'
boxesvars['type'] = 'Intel Gigabit Ethernet (e1000)'
boxesvars['replicateQEMU'] = 'on'
boxesvars['MAC1'] = '0c:cb:a8:90:00:00'
boxesvars['MAC2'] = '0c:50:a2:8a:00:00'
with open('newestinventory.ini', 'w') as configfile:
        config.write(configfile)
